#!/usr/bin/env ruby

require 'chef/rest'
require 'chef/node'
require 'chef/knife'
require 'chef/config'
require 'vcr'
require 'ruby-debug'
require 'yajl/json_gem' 

VCR.config do |c|
  c.ignore_hosts '127.0.0.1'
  c.cassette_library_dir = 'fixtures/vcr_cassettes'
  c.stub_with :webmock # or :fakeweb
  #c.default_cassette_options = { :record => :once }
end

class ChefServer < Chef::Knife
  def initialize
    #Chef::Config[:client_key] = "~/.chef/joe_live.pem"
    Chef::Config[:node_name] = 'Joe'
    Chef::Config[:chef_server_url] = 'http://109.144.14.214:4000' # testing
    Chef::Config[:client_key] = "#{File.dirname(__FILE__)}/joe_testing.pem"
    #Chef::Config[:node_name] = 'Joe'
    #Chef::Config[:chef_server_url] = 'http://109.144.14.214:4000' # testing
    @rest = Chef::REST.new(Chef::Config[:chef_server_url])
    super
  end

  def nodes
    rest.get_rest("/nodes")
  end

  def node node_name
    rest.get_rest("/nodes/#{node_name}")
  end

end

VCR.use_cassette('node_roles_real') do #, :erb => {:chef_url => "109.144.14.214", :first_server_id => "blah", :second_server_id => "blue"}) do
  chefserver = ChefServer.new
  #nodes = chefserver.nodes
  ##puts nodes

  #nodes.each do |node|
    debugger
    node_data = chefserver.node("i-000FFTpR")# node[0])
    roles = node_data.roles #if node_data.attribute?(:roles)
    puts "#{node_data.name} roles #{roles || "none"}"
  #end
end
